# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kindling

builds:
  - id: kindling-cli
    dir: cli
    main: .
    binary: kindling
    ldflags:
      - -s -w
      - -X github.com/jeffvincent/kindling/cli/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: kindling-cli
    builds:
      - kindling-cli
    name_template: "kindling_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - ids:
      - kindling-cli
    repository:
      owner: kindling-sh
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/kindling-sh/kindling"
    description: "Local Kubernetes dev environments powered by Kind"
    license: "Apache-2.0"
    commit_author:
      name: kindling-bot
      email: bot@kindling.sh
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    dependencies:
      - name: kind
      - name: kubectl
    test: |
      system "#{bin}/kindling", "version"

release:
  github:
    owner: kindling-sh
    name: kindling
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
